### ISSUE TITLE
Plugin doesnt work unless you delete the config and force reload and clearcache after startup

### ISSUE THREAD

**Issue by BillyGalbreath** [lishid/Orebfuscator#135] opened 2016-11-23 09:47 UTC
Not sure how to title this one.

It seems that /ofc reload is doing something weird and not obfuscating how its supposed to, UNLESS you delete the config.yml file and then /ofc reload /ofc clearcache.

This can be seen easily (with an xray mod) since EngineMode 2 is the default and it does a "blanket effect" of random blocks. When the plugin is working correctly this blanket effect is noticeable. When the plugin doesnt work right this blanket effect is non existent and instead the random blocks seem to be scattered throughout the underground.

This problem exists on fresh boots with a customized config.yml too. So basically I have to delete my config.yml on server start, then reload and clearcache just to be able to use the plugin somewhat effectively.

More information (and screenshot): https://www.spigotmc.org/threads/orebfuscator.145252/page-6#post-2038997 See posts 110-116.

I've been testing using AmbientOcclusion's X-Ray mod version 45 on PaperSpigot 1.11 (git-Paper-930)

Video: https://www.youtube.com/watch?v=w8m8a5XGo1g

**Comment by RoboMWM** [comment] 2016-11-23 11:45
Did you relog after reloading?

**Comment by BillyGalbreath** [comment] 2016-11-23 11:45
Of course. Check video.

**Comment by RoboMWM** [comment] 2016-11-23 11:57
Going to guess this has something to do with the airgenerator thingy (AntiTexturePackAndFreecam option)

**Comment by RoboMWM** [comment] 2016-11-27 23:12
Ok, so the plugin is working fine for me (using engine mode 1).

However, the air generator is acting wonky. Instead of making all ores into stone, it's making some of these ores (presumably this "some" is the `AirGeneratorMaxChance` value) into air blocks instead of stone blocks.

It looks like you have the same issue here - some of the blocks that contain the actual ores are turned into air instead.

So this is an issue with the `AntiTexturePackAndFreecam` feature (which should be applied to all non-visible areas of a chunk) - please retitle as such.

**Comment by Aleksey-Terzi** [comment] 2016-12-02 04:31
Thanks for details, I will test it and let you know results.
Probably as suggested RoboMWM this is somehow related to air generator.

**Comment by Aleksey-Terzi** [comment] 2016-12-04 09:34
Bug is reproduced and fixed.

Problem happened because of STONE was not in list for obfuscation.
But this material should be added by default for Normal world (the same for The End and ENDER_STONE and Nether and NETHERRACK)
Why it worked when deleting config file - because of on config creation it set STONE correctly.

Latest changes committed for now in DevotedMC fork, so you can take sources from here.

Another way to fix issue - add STONE manually to config file to ObfuscateBlocks section.

**Comment by FataLeeer** [comment] 2016-12-27 23:06
Not "blanced"

1.11 why not 'blanked' ?
Orebfuscator 4.20
Config - default(engine mode - 2)
ProtocolLib v4.1.0 or ProtocolLib 4.2.0-SNAPSHOT-b333

`ConfigVersion: 13
Booleans:
  UseCache: true
  Enabled: true
  UpdateOnDamage: true
  NoObfuscationForMetadata: true
  NoObfuscationForOps: false
  NoObfuscationForPermission: false
  LoginNotification: true
Integers:
  MaxLoadedCacheFiles: 64
  DeleteCacheFilesAfterDays: 0
  EngineMode: 2
  InitialRadius: 1
  UpdateRadius: 2
Strings:
  CacheLocation: orebfuscator_cache
  NoObfuscationForMetadataTagName: NPC
Lists:
  TransparentBlocks: []
  NonTransparentBlocks: []
Worlds:
  Default:
    Types:
    - DEFAULT
    Enabled: true
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    DarknessBlocks:
    - MOB_SPAWNER
    - CHEST
    Mode1Block: STONE
    RandomBlocks: []
    ObfuscateBlocks: []
    ProximityHider:
      Enabled: true
      Distance: 8
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - DISPENSER
      - MOB_SPAWNER
      - CHEST
      - DIAMOND_ORE
      - WORKBENCH
      - FURNACE
      - BURNING_FURNACE
      - ENCHANTMENT_TABLE
      - EMERALD_ORE
      - ENDER_CHEST
      - ANVIL
      - TRAPPED_CHEST
  Normal:
    Types:
    - NORMAL
    Mode1Block: STONE
    RandomBlocks:
    - STONE
    - COBBLESTONE
    - WOOD
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - TNT
    - MOSSY_COBBLESTONE
    - OBSIDIAN
    - DIAMOND_ORE
    - REDSTONE_ORE
    - CLAY
    - EMERALD_ORE
    ObfuscateBlocks:
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - CHEST
    - DIAMOND_ORE
    - REDSTONE_ORE
    - GLOWING_REDSTONE_ORE
    - EMERALD_ORE
    - ENDER_CHEST
  TheEnd:
    Types:
    - THE_END
    Mode1Block: ENDER_STONE
    RandomBlocks:
    - BEDROCK
    - OBSIDIAN
    - ENDER_STONE
    - PURPUR_BLOCK
    - END_BRICKS
    ObfuscateBlocks:
    - ENDER_STONE
  Nether:
    Types:
    - NETHER
    Mode1Block: NETHERRACK
    RandomBlocks:
    - GRAVEL
    - NETHERRACK
    - SOUL_SAND
    - NETHER_BRICK
    - QUARTZ_ORE
    ObfuscateBlocks:
    - NETHERRACK
    - QUARTZ_ORE
`

**Comment by RoboMWM** [comment] 2016-12-28 01:30
@FataLeeer a commit was already pushed regarding this issue. If you wish to contribute to this issue report, first ensure that you are running the latest version of the code found on the repository (yes, you will have to manually compile it.)

Especially for this issue, you will also need to supply pictures.

**Comment by bigsmileling** [comment] 2016-12-30 17:15
Is not working properly, when i do /ofc reload is not working.

I have to delete the config and do ofc reload for make it work as i want, but i want edit the chest and furnaces detection and i can't because stop working as i want.

Working bad: https://youtu.be/bm86bQ4vObk

Working fine: https://youtu.be/DHrI6xkrDyE

**Comment by Aleksey-Terzi** [comment] 2016-12-31 06:32
Probably problem happened because of cache (created with pre 4.2.1) was not cleared.
Could you please do the following and let me know if problem solved or no:
1) Execute command /ofc clearcache
2) Restart client

**Comment by RoboMWM** [comment] 2016-12-31 06:50
@Aleksey-Terzi, he says it works with the latest update:

> EDIT: Working with 4.2.1

**Comment by Aleksey-Terzi** [comment] 2016-12-31 11:04
Oh, thanks
Misread

Closing issue,

**Closed by Aleksey-Terzi** 2016-12-31 11:04 UTC

**Comment by Dreadonator** [comment] 2017-01-13 23:03
I can not find 4.2.1 just 4.2.0 Does anyone have a compiled jar for me?

**Comment by DrkMatr1984** [comment] 2017-01-14 17:18
I'll fork and add a release jar to my fork later for u

**Comment by Aleksey-Terzi** [comment] 2017-01-14 18:46
@Dreadonator

Latest compiled version is here: https://www.dropbox.com/s/o3o47vgufpcrok9/orebfuscator-4.2.1-SNAPSHOT.jar?dl=0

**Comment by DrkMatr1984** [comment] 2017-01-14 22:17
Oh! he beat me to it :) Thanks @Aleksey-Terzi 
It's also here:
https://github.com/DrkMatr1984/Orebfuscator/releases
If you need it :)

**Comment by ScuroK** [comment] 2017-01-16 10:41
Thanks alot!!

**Comment by ProgrammerDan** [comment] 2017-01-16 16:02
BTW official release is live: https://github.com/lishid/Orebfuscator/releases/tag/4.2.1

**Comment by Dreadonator** [comment] 2017-01-16 17:11
Will you also update the spigot page?
