### ISSUE TITLE
Item frames on 1.10.2 and NPC skins

### ISSUE THREAD

**Issue by ScuroK** [lishid/Orebfuscator#113] opened 2016-06-30 08:28 UTC
I have a problem on latest spigot. In my shop the item frames seems to disappear. some do and some dont. if i rejoin the server they are here again. if i dont join the server where all the item frames are, they vanish. not all but some do. they seems gone untill i rejoin the server.

the second problem i found is that citizens NPCs dont have a skin.

After removing orebuscator the problem was gone.

**Comment by Aleksey-Terzi** [comment] 2016-06-30 09:51
Could you please provide more information.

What full version of Spigot, version of Orebfuscator?
Do you have any errors in the log?
Could you please provide your Orebfuscator's config?

> the second problem i found is that citizens NPCs dont have a skin.

Could you please provide more info about this, what NPC and skins you mean?

**Comment by ScuroK** [comment] 2016-06-30 10:16
see my log and config attached

[log and config.zip](https://github.com/lishid/Orebfuscator/files/341196/log.and.config.zip)

**Comment by ScuroK** [comment] 2016-06-30 10:31
[screenshots.zip](https://github.com/lishid/Orebfuscator/files/341218/screenshots.zip)

**Comment by ScuroK** [comment] 2016-06-30 10:33
regarding the NPCs: they seem to be invisible sometimes and sometimes they have the default steve skin. join the server again usually solve it. without orebuscator this bugs dont happen. i tested it.

**Comment by Aleksey-Terzi** [comment] 2016-07-01 07:10
I cannot reproduce problem and haven't in my logs any errors.

You provided part of your log and I see here a lot of errors at the start of server from another plugin.
But could you please look at your server's log and search for Orebfuscator-related errors?

Also could you please try to test issue with frames with just Orebfuscator on the server and provide me full log file if you still have issue?

You told that issue disappears if you are removing Orebfuscator plugin, though this doesn't mean that bug in Orebfuscator.
Week ago someone posted issue #109 with a lot of errors in the log caused by Orebfuscator and Dynmap plugins, but according to logs actually problem was because of ChestShop.
We could have here the same situation.

Problem with NPC I did not try to reproduce since not sure what I have to do.
Though I've tried standard villagers (if you meant them) - they are working ok for me.

Could you please let me know what plugin are you using?
Also could you please to test this issue with just your NPC plugin (if you are using it) and Orebfuscator without any other plugins and if you still have problems - then provide me full log file?

**Comment by ScuroK** [comment] 2016-07-12 19:27
all i can say: still on the newest spigot version of today the problem exists.
i have also removed the cheshsop plugin. and i have the latest protocollib runnig:
i removed orebuscator and the problem is gone.

maybe it is incompatible with some of my plugins...

**Comment by ScuroK** [comment] 2016-07-12 19:51
i also found double entries in the worlds list after updating. and the /oft enebale <worldname> does not react anymore.

**Comment by ScuroK** [comment] 2016-07-12 19:59
the bug happens in a disabled world (no ofc running) it only affect some chunks of the shop. normally some still have the item frames. but its not broken chunks because it happen randomly

**Comment by Aleksey-Terzi** [comment] 2016-07-15 05:53
> i have also removed the cheshsop plugin. and i have the latest protocollib runnig:

After you removed chestshop - problem still exist?

> maybe it is incompatible with some of my plugins...

Looks like yes, but its interesting with what plugin(s) it is incompatible.
But I cannot do this until I will setup the same environment as yours and reproduce problem.  
Therefore if you can provide information what I have to install and do to see error this could be useful.

Also do you have any Orebfuscator-related errors in your log file?

**Comment by ScuroK** [comment] 2016-08-01 15:13
I found the following.

1. I install OFC and leave the config file on default. - It works. No problems.
2. I do /ofc disable WORLD. - The world is disabled. Still no problems. But i can not find the disabled world listed in the config!
2. I manually add worlds to the config blacklist. (see the files above) - Problem occures

**Comment by ScuroK** [comment] 2016-08-01 15:16
Yes i removed chestshop. 
I gave it up for now... :(

**Comment by ScuroK** [comment] 2016-08-01 15:27
It happens only in my shop, where many item frames are spread. the shop is multiple chunks big. 
the bug makes just some frames invisible. sometimes in this chunk, sometimes in another.

maybe it have something todo with the spigot entities-settings?
maybe the distance settings?

i have no clue!
but i found another guy on the bukkit comments page had the same issues

**Comment by Aleksey-Terzi** [comment] 2016-08-02 07:41
When spigot was upgraded from 1.9.2 to 1.9.4 - then stopped to work refreshChunk function - it did exactly the same thing as you describing here:
1) entities disappearing
2) problems with signs and frames

In Orebfuscator this problem was successfully fixed.

But maybe this function is not fixed somewhere in another plugins you are using now.
Maybe somehow in combination with Orebfuscator this plugin is doing refreshChunk or similar operations which are leading to disappearing entities and frames.

But I cannot reproduce this problem therefore I need your guidance on how to reproduce it.  

Are you able to reproduce problem without any other plugins?
If yes, then could you please provide step by step description of what I have to do to see it?

If problem could be reproduced only with other plugins then could you please provide step by step description of what I have to do to setup server and reproduce problem?

**Comment by ScuroK** [comment] 2016-08-02 19:44
@Aleksey-Terzi 

I am not sure but i THINK i found the guilty plugin:
https://www.spigotmc.org/resources/lwc-unofficial-entity-locking.2162/

Its very important for me to use this plugin. becaus its the only LWC with UUID support.

here is the config: 
[core.yml.zip](https://github.com/lishid/Orebfuscator/files/397962/core.yml.zip)

I do not use any of its entity features. but i need it because its the only updated LWC.

Here is a Worldedit-Schematic of my shop:
[shop.schematic.zip](https://github.com/lishid/Orebfuscator/files/397966/shop.schematic.zip)

1. install OFC and disable the main world
2. install the lwc and use my settings.
3. setup my shop from schematic in the main world
4. Set a warp with essentials inside the shop
5. tp between different worlds and shop and also between other locations in same world and shop.

I hope this can reproduce the bug. If not i can give you more detailed steps including other (still installed) plugins.

**Comment by Aleksey-Terzi** [comment] 2016-08-04 10:37
Thank you for details, I will investigate it and then provide response.

**Comment by Azfaloth** [comment] 2016-08-15 05:57
I have the same issue as reported in comments by Master Mithrandir. Cows etc become invisible sometimes and need a relog to become visible again. I am also using mythic mobs. The best way to replicate it is to teleport to and away from the chunks repeatedly and eventually they go invisible at some point.

**Comment by Aleksey-Terzi** [comment] 2016-08-16 04:44
@ScuroK

Sorry for delay, but I've finally did tests and still cannot reproduce problem.

I have following plugins:

1) EntityLWC.jar (latest version from here https://www.spigotmc.org/resources/lwc-unofficial-entity-locking.2162/)

2) worldedit-bukkit-6.1.3.jar

3) orebfuscator-4.1.2-SNAPSHOT.jar

4) Latest ProtocolLib.jar

I've copied your config files and setup shop from schematic file, but have following changes in Orebfuscator's config:

1) Removed all worlds from black list

2) Set NoObfuscationForOps to false (since I've tested as Op)

Then I tried to teleport to distant lands and then back - nothing happened - signs still shown text and frames still had items.  
    
Could you please try to create server from the start and reproduce error and then tell me exact steps? Also would be good if you will provide me map and exact list of plugins and their configs.

@Azfaloth

Could you please provide step by step description of how should I setup server and what I should do to see the problem?

**Comment by ScuroK** [comment] 2016-08-16 19:47
@Aleksey-Terzi 
Here is my test server folder for download:
https://dl.dropboxusercontent.com/u/30946963/LOKALSERVER%20F%C3%9CR%20TEST/CraftBukkit.zip

I tested with xray from:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292688-xray-mod-1-6-4-1-10-vanilla-forge-liteloader


1. /spawn
2. /warp shop and walkaround the shop
3. /back or /world repeat a few times. always look arround the shop and check if all item fraes still here.

tp between shop and spawn or shop and other worlds a few times. u will see some of the item frames in the shop will disappear.

Pleaselet me know when u donloaded the folder so i can delete it from my dropbox. Thanks!

**Comment by RoboMWM** [comment] 2016-08-17 03:42
> I tested with xray from:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292688-xray-mod-1-6-4-1-10-vanilla-forge-liteloader

Have you tried with just the vanilla client? Perhaps it's a bug with forge and/or a mod.

**Comment by Aleksey-Terzi** [comment] 2016-08-17 17:37
@ScuroK

I've downloaded it, thank you.
But will look little later.
Also I'm agree with RoboMWM about why I need to use xray plugin, but I will try it by myself and look :)

**Comment by ScuroK** [comment] 2016-08-18 09:24
@Aleksey-Terzi 
@RoboMWM 

I tested it with a vanilla client aswell - no difference!

**Comment by Aleksey-Terzi** [comment] 2016-08-18 09:31
Ok, thank you for confirmation.

**Comment by Aleksey-Terzi** [comment] 2016-08-23 03:40
@ScuroK

Just to let you know status.
I've reproduced bug using your compilation.
Also I was able to reproduce problem with just Orebfuscator and ProtocolLib plugin, so look like this is Orebfuscator's bug.

**Comment by ScuroK** [comment] 2016-08-23 05:48
Oh im glad you finally reproduced it! 
i hope you guys can find a way to fix it soon.

thx!

**Comment by ScuroK** [comment] 2016-08-24 17:49
@Aleksey-Terzi 
Im not 100% sure but it seems like the bug is gone in latest version?

**Comment by ScuroK** [comment] 2016-08-24 17:56
Unfortunately the bug still exists in latest version. :(

**Comment by ScuroK** [comment] 2016-08-27 20:13
Hey Guys, is there any chance you will fix  this bug? otherwise i need to find another anti xray solution :/

**Comment by RoboMWM** [comment] 2016-08-27 22:11
Patience. Tagging us (especially me) won't get this solved any faster.

**Comment by ScuroK** [comment] 2016-08-28 08:37
im sorry for tagging you.
i just wanted to know if you work on it or if this bug cant be solved.

i did all i can to help u as good as i can.

**Comment by Aleksey-Terzi** [comment] 2016-08-28 15:34
@RoboMWM

I agree with this. Thanks for support.

@ScuroK

Sorry for time you waited.
Bug is fixed and fix will be in the next release.
But since I'm guessing you want to apply update ASAP, you can either compile plugin from latest sources on DevotedMC fork or you can use my compilation: https://www.dropbox.com/s/fizaact5qza3x4c/orebfuscator-4.1.5-SNAPSHOT.jar?dl=0

**Comment by ScuroK** [comment] 2016-08-28 16:00
Thank you so much for this!! <3 <3 <3 <3

**Comment by Aleksey-Terzi** [comment] 2016-09-12 03:17
Fix is in latest release, so I'm closing issue.

**Closed by Aleksey-Terzi** 2016-09-12 03:17 UTC
