### ISSUE TITLE
Right Click to Reveal

### ISSUE THREAD

**Issue by teegah** [lishid/Orebfuscator#121] opened 2016-08-14 18:56 UTC
When players are mining they have to right click stone around them to check if its an ore or not. All ores are invisible, and players have to right click when mining to check for ores. We are using the 1.10 with paperspigot. We think that something in paperspigot is conflicting with orebfuscator which is preventing block updates from being sent correctly but we don't know for sure.

**Comment by RoboMWM** [comment] 2016-08-14 19:01
Please paste config

**Comment by teegah** [comment] 2016-08-14 22:10
http://pastebin.com/gRi9VpxV

**Comment by teegah** [comment] 2016-08-16 04:20
Any ideas?

**Comment by Aleksey-Terzi** [comment] 2016-08-16 04:47
@teegah

Thanks for config, could you please also provide full log file so I could check if it has errors related to Orebfuscator?

**Comment by teegah** [comment] 2016-08-16 12:30
@Aleksey-Terzi 

Hey, I'm unable to provide a log file since it contains some sensitive information and is quite large, we've gone through it thought and there are no errors related to Orebfuscator. We are quite positive that the issue is with paperspigot since Orebfuscator works fine with spigot.

**Comment by Aleksey-Terzi** [comment] 2016-08-16 12:37
I've did tests with latest paperspigot (from August 15) and was not able to reproduce problem.
Maybe problem somehow relates on world data.

Could you please provide beginning of the log (all initialization part) and try to find any Orebfuscator-related errors and provide these parts too?

**Comment by RoboMWM** [comment] 2016-08-16 16:05
To add to this, I also use paper and don't have the issues you described (I used to, but that was when I had `update-radius` set to 4, which is too large for spigot/paper).

**Comment by Kowaman** [comment] 2016-08-18 07:58
Hey, another dev from the server with the issue. Isssue was that a custom mining plugin cancels blockbreakevent and does the logic itself, thus not causing blocks to update. I would recommend a config option to listen on cancelled block break events to the author.

**Comment by Aleksey-Terzi** [comment] 2016-08-18 09:37
@Kowaman

Yes, this could be the reason.  
But if some plugin is doing non-standard processing of some events then it is responsible for being compatible with another plugins (in our case with Orebfuscator)  
I would recommend to use static method com.lishid.orebfuscator.obfuscation.BlockUpdate.updateByLocations to make sure that blocks have been updated on Orebfuscator side.  
I'm using it in my another plugin CastleGates which is doing breaks and placements without firing standard events.

**Comment by Aleksey-Terzi** [comment] 2016-08-25 03:13
I'm closing this issue because of look like problem not with Orenfuscator but with non-standard behavior of another plugin.

**Closed by Aleksey-Terzi** 2016-08-25 03:13 UTC
