### ISSUE TITLE
Orebfuscator Error in console

### ISSUE THREAD

**Issue by OneLeggedMan** [lishid/Orebfuscator#94] opened 2016-05-11 18:21 UTC
Hello please help me solve this error as I can't seem to fix it. Here is the console log

http://pastebin.com/WJf2iH68

**Comment by ProgrammerDan** [comment] 2016-05-11 18:23
Thanks for the report. Orebfuscator does not yet support 1.9.3 or 1.9.4 -- an upgrade supporting those versions is in the works but is not yet available due to changes in Bukkit.

As this is a duplicate of #92 I am closing for now; please watch #92 for update on a compatible version.

**Closed by ProgrammerDan** 2016-05-11 18:23 UTC

**Comment by ProgrammerDan** [comment] 2016-05-11 19:18
@Aleksey-Terzi Looked a bit more closely then me at your issue :).

Please use this version: https://github.com/lishid/Orebfuscator/releases/tag/v3.0.6-R3-legacy

as you are still using Spigot 1.8.8.
