### ISSUE TITLE
Craftbook + ChestShop + OreOrb = Recursive Crash?

### ISSUE THREAD

**Issue by Kainzo** [lishid/Orebfuscator#109] opened 2016-06-20 20:42 UTC
https://github.com/lishid/Orebfuscator/issues/100
PaperSpigot 1.9.4 (last version)
vR: Orebfuscator 4.1.0 for 1.10

**Comment by ProgrammerDan** [comment] 2016-06-20 20:43
Can you please post via pastebin or other paste site the logs of the incident, and the versions of CraftBook and ChestShop you are using? 


Thanks!

**Comment by Aleksey-Terzi** [comment] 2016-06-21 04:46
@Kainzo 

If you about error posted on http://dev.bukkit.org/bukkit-plugins/orebfuscator then I think this error is not specific to "ChestShop + Orebfusactor" and will happen for any plugin which is handling BlockPistonRetract.
From log you provided on dev.bukkit.org - crash happened also in Dynmap plugin.

> vR: Orebfuscator 4.1.0 for 1.10

According to your log - server is using Orebfuscator 4.0.14

I propose you to try to reproduce problem without Orebfuscator and then without ChestShop.

Please let me know your results.

**Comment by Aleksey-Terzi** [comment] 2016-06-27 03:25
Since there are no additional information - I'm closing this issue.

**Closed by Aleksey-Terzi** 2016-06-27 03:25 UTC
