### ISSUE TITLE
Proximity detect changes things into stone even when next to them. 

### ISSUE THREAD

**Issue by manmadehuman** [lishid/Orebfuscator#131] opened 2016-10-08 01:31 UTC
running 4.1.8

I can show you better than I can explain in it - https://gfycat.com/ConsciousPossibleGnat

Also some players couldn't use enchanting tables at all because every time they'd click on them, it would become stone. and they'd get stuck. 

Here is my config - http://pastebin.com/DTzpeAna
My Plugins list - http://pastebin.com/KLAZtaHb
Just incase, here is my spigot and bukkit yml files - http://pastebin.com/HTK2a2D6

Please let me know if you need anything else.

**Comment by Aleksey-Terzi** [comment] 2016-10-09 06:24
I not able reproduce problem, but have some suggestions about config:

1) There are actually no reason to set UpdateRadius larger than 3: https://github.com/lishid/Orebfuscator/wiki/About-deobfuscation-on-block-break

Therefore I recommend to set it for example to 3 o avoid possible issues

Could you please do this and look if something changed?

2) If nothing helped you can try to set UpdateRadius to 1 and look if something changed

3) Try to set DarknessHideBlocks = false just for experiment

Please let me know your results

**Comment by manmadehuman** [comment] 2016-10-09 06:31
Thanks - I had update radius set higher out of a bad assumption of what it meant. Thanks for the clarification. 

I set it to 3 - Also I have set DarknessHideBlocks to false and I will let you know if players still experience the issue. 

Just for more info.

Thanks!

**Comment by manmadehuman** [comment] 2016-10-13 03:58
Still having the issue afting making the settings changes. 

At first not everyone noticed the issue. I wasn't seeing it and everything seemed to be working.  But after a few hours of play, now chests are being stone directly in front of us again. It seemed to take a while for it start again after making those setting changes.  

I made all the recommended settings above. 

thanks!

**Comment by RoboMWM** [comment] 2016-10-13 04:06
Try without using other plugins, if possible. I know I used to have this issue with Orebfuscator before the DevotedMC team picked it up, and simply fixed it by not using it. But I've seen another server use it successfully (and it seems they're using the default settings), albeit they're a semi-vanilla server (no shop plugins or the like).

**Comment by manmadehuman** [comment] 2016-10-13 04:11
I have a test server I could do that with when I get a chance. Just not sure how much time I'll have to spend on it before I know if it works or no lol. Seems like an issue, if related to another plugin, that would take ages to narrow down lol.  May just end up keeping it off.

**Comment by Aleksey-Terzi** [comment] 2016-10-13 04:23
@manmadehuman 
Problem with issue you shown is that I not able to reproduce it.
If you can prepare zip/7z archive with all server/map files and provide step by step description of what I have to do to see the problem - that would be very useful.

**Comment by Aleksey-Terzi** [comment] 2017-04-29 08:41
Closing issue.
If you still have some questions, then please reopen it.

**Closed by Aleksey-Terzi** 2017-04-29 08:41 UTC
